
all: YodafyClienteTCP.class YodafyServidorConcurrente.class

YodafyClienteTCP.class: YodafyClienteTCP.java
	javac $^

YodafyServidorConcurrente.class: YodafyServidorConcurrente.java ProcesadorYodafy.java
	javac $^
